// <auto-generated />
using System;
using BOQNETFootballerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOQNETFootballerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250514173827_FootballerStats")]
    partial class FootballerStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BOQNETFootballerAPI.Data.Models.Footballer", b =>
                {
                    b.Property<int>("FootballerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Club")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.HasKey("FootballerId");

                    b.ToTable("Footballer");
                });

            modelBuilder.Entity("BOQNETFootballerAPI.Data.Models.FootballerMatchStats", b =>
                {
                    b.Property<int>("FootballerMatchStatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FootballerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsScored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PassCompletionPercentage")
                        .HasColumnType("REAL");

                    b.HasKey("FootballerMatchStatsId");

                    b.ToTable("FootballerMatchStats");
                });
#pragma warning restore 612, 618
        }
    }
}
